version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: eraktkendra
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - my-network

  frontend:
    depends_on:
      - backend
    image: barivikranth36/e_raktkendra_frontend:latest
    ports:
      - 3000:3000

    networks:
      - my-network


  backend:
    depends_on:
      - mysql
    image: barivikranth36/eraktkendra:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_PORT: 3306
    ports:
      - 9090:9090

    networks:
      - my-network

volumes:
  mysql-volume:

networks:
  my-network: