version: '3'
services:
  mysql:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: eraktkendra
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - my-network

  frontend:
    depends_on:
      - backend
    image: imshukla/eraktkendra_frontend:latest
    ports:
      - "3000:3000"

    networks:
      - my-network

  backend:
    depends_on:
      - mysql
    image: imshukla/eraktkendra_backend:v1
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
    ports:
      - 9090:9090

    networks:
      - my-network

volumes:
  mysql-volume:

networks:
  my-network:
