version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: eraktkendra
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - my-network

  backend:
    depends_on:
      - mysql
    image: barivikranth36/e_raktkendra:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eraktkendra?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - 9090:9090

    networks:
      - my-network

volumes:
  mysql-volume:

networks:
  my-network: